#ubuntu base image
FROM ubuntu:latest

MAINTAINER Khaja "devopsprofessionaluk@gmail.com"

RUN apt-get update -y

RUN apt-get install -y python-pip python-dev build-essential

EXPOSE 5000

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY rest-flask.py /usr/src/app

RUN pip install Flask

CMD ["python", "rest-flask.py"]
