#ubuntu base image
FROM ubuntu
RUN apt-get update
RUN apt-get install -y python-pip git
RUN pip install flask
EXPOSE 5000
RUN git clone https://github.com/kchandan/utils.git
CMD ["python", "/utils/rest-flask.py"]
